#########################
## Sass Lint Config File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html'
  formatter: html
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# File Options
files:
  include: 'src/sass/**/*.s+(a|c)ss'
  ignore:
    - 'src/sass/base/_fontfaces.*'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  no-debug: 1
  no-ids: 2
  hex-notation:
    - 1
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
  property-sort-order: 0
  space-after-colon: 2
  space-before-bang: 2
  space-before-brace: 2
